import { staticProductSeoRecords } from './productSeoData.js';

export const SITE_URL = 'https://thefuturex.in';

export const coreRoutes = [
  { path: '/', label: 'Home', changefreq: 'daily', priority: '1.0' },
  { path: '/shop/all', label: 'Shop', changefreq: 'daily', priority: '0.9' },
  { path: '/smart-bands', label: 'Smart Bands', changefreq: 'weekly', priority: '0.8' },
  { path: '/smart-rings', label: 'Smart Rings', changefreq: 'weekly', priority: '0.8' },
  { path: '/bladeless-fan', label: 'Bladeless Fan', changefreq: 'weekly', priority: '0.8' },
  { path: '/smart-monitoring', label: 'Smart Monitoring', changefreq: 'weekly', priority: '0.8' },
  { path: '/smart-glasses', label: 'Smart Glasses', changefreq: 'weekly', priority: '0.8' },
  { path: '/gifting-store', label: 'Gifts', changefreq: 'weekly', priority: '0.7' },
  { path: '/new-arrivals', label: 'New Arrivals', changefreq: 'daily', priority: '0.8' },
  { path: '/best-sellers', label: 'Best Sellers', changefreq: 'daily', priority: '0.8' },
  { path: '/track-order', label: 'Track Your Order', changefreq: 'monthly', priority: '0.5' },
  { path: '/raise-complaint', label: 'Give Feedback', changefreq: 'monthly', priority: '0.5' },
  { path: '/register-warranty', label: 'Register Your Product', changefreq: 'monthly', priority: '0.5' },
];

const toBlogSlug = (title = '') =>
  String(title)
    .toLowerCase()
    .trim()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const blogPlanTitles = [
  'How Accurate Is Smart Band Sleep Tracking, Really?',
  'TFX5 AI Smart Band: Full Review After 30 Days of Wear',
  'How to Read Your Smart Band\'s Recovery Score',
  'Smart Band Battery Dying Fast? 7 Common Fixes',
  'What Your Resting Heart Rate Trend Is Actually Telling You',
  'Smart Band vs Apple Watch: Do You Need the Extra Cost?',
  'How to Set Up Your TFX5 Smart Band in Under 5 Minutes',
  'Do Smart Bands Actually Help You Lose Weight?',
  'Best Smart Band Settings for Runners',
  'Understanding Step Count Accuracy on Wrist Wearables',
  'How Smart Bands Track Stress and What to Do With That Data',
  'Water Resistance Ratings Explained: Can You Shower With Your Band?',
  'Smart Band Notifications Not Working? Troubleshooting Guide',
  'How Often Should You Charge Your Smart Band?',
  'Smart Bands for Seniors: What to Look for',
  'Menstrual Cycle Tracking on Smart Bands: How It Works',
  'Smart Band Screen Protectors: Do You Need One?',
  'How to Interpret Your Weekly Activity Report',
  'Smart Bands and Blood Pressure: What They Can and Can\'t Do',
  'Choosing a Smart Band Strap Material: Silicone vs Metal vs Fabric',
  'Smart Band Syncing Issues: Bluetooth Troubleshooting',
  'Can a Smart Band Replace a Fitness Tracker for Gym Training?',
  'How TFX Smart Bands Calculate Calories Burned',
  'Smart Bands for Kids: Are They Worth It?',
  'Setting Realistic Step Goals Based on Your Lifestyle',
  'Smart Band Skin Irritation: Causes and Fixes',
  'How to Export Your Smart Band Health Data',
  'Smart Band Firmware Updates: Why They Matter',
  'Best Smart Bands Under Rs 3,000 in India',
  'TFX5 vs Older TheFutureX Band Models: What\'s Changed',
  'Smart Ring vs Smart Band: Which One Should You Actually Buy?',
  'TFX Display Pro Smart Ring: Full Review',
  'How to Find Your Correct Smart Ring Size',
  'Smart Ring Battery Life: What to Realistically Expect',
  'Can You Wear a Smart Ring While Working Out?',
  'Smart Rings and Sleep Tracking: Why They\'re So Comfortable Overnight',
  'Wireless Charging for Smart Rings: How It Works',
  'Smart Ring Not Syncing? Common Fixes',
  'Do Smart Rings Work for People With Larger or Smaller Fingers?',
  'Smart Ring Materials Explained: Titanium vs Ceramic vs Steel',
  'How Accurate Are Smart Rings for Heart Rate?',
  'Can You Shower or Swim With a Smart Ring?',
  'Smart Ring Etiquette: Wearing One Alongside Regular Jewelry',
  'How Smart Rings Measure Readiness and Recovery',
  'Best Smart Rings for Side Sleepers',
  'Smart Ring Battery Died: Will You Lose Your Data?',
  'Understanding the Display on the TFX Display Pro Smart Ring',
  'Smart Rings for Office Workers: Subtle Health Tracking',
  'How Long Do Smart Rings Actually Last?',
  'Smart Ring Skin Reactions: What Causes Them',
  'Setting Up Smart Ring Notifications and Alerts',
  'Smart Rings and Nail Length: Any Issues?',
  'Choosing a Smart Ring Color to Match Your Style',
  'Smart Ring vs Traditional Fitness Tracker: A Cost Comparison',
  'Can Smart Rings Detect Irregular Heartbeats?',
  'Cleaning and Maintaining Your Smart Ring',
  'Smart Rings for Couples: Shared Health Goals',
  'Traveling With a Smart Ring: TSA and Airport Questions',
  'How Smart Rings Handle Temperature Tracking',
  'Is a Smart Ring Worth It If You Already Own a Smartwatch?',
  'Why Bladeless Fans Are Safer for Homes With Kids and Pets',
  'TFX LuxAir Pro vs AirWall Pro: Which Bladeless Fan Should You Buy?',
  'How Bladeless Fans Actually Work Explained Simply',
  'Bladeless Fan vs Traditional Fan: Airflow and Noise Compared',
  'Best Bladeless Fans for Small Bedrooms',
  'How to Clean a Bladeless Fan Properly',
  'Do Bladeless Fans Use More Electricity Than Regular Fans?',
  'TFX Advance All-Season Fan: Is It Worth the Higher Price?',
  'Wall-Mounted vs Tower Bladeless Fans: Pros and Cons',
  'Bladeless Fans With Air Purifiers: Do They Actually Help Allergies?',
  'How Quiet Are Bladeless Fans, Really? Decibel Guide',
  'Choosing a Fan for a Home Office: Airflow Without Noise',
  'Bladeless Fan Not Turning On? Troubleshooting Guide',
  'Can Bladeless Fans Heat a Room in Winter?',
  'HEPA Filters Explained: What TFX HEPA PureAir Pro Actually Filters',
  'Best Bladeless Fans for Large Living Rooms',
  'Bladeless Fan Remote Not Working? Common Fixes',
  'Bladeless Fans and Energy Bills: What to Expect Monthly',
  'Are Bladeless Fans Safe to Leave Running Overnight?',
  'How to Choose Between Cooling-Only and All-Season Fans',
  'Bladeless Fan Maintenance Schedule: What to Check and When',
  'Best Placement for a Bladeless Fan in a Studio Apartment',
  'Bladeless Fans for Nurseries: Safety Considerations',
  'Do Bladeless Fans Actually Feel Different From Regular Fans?',
  'TFX Breeze Pro Review: Motor Upgrade Explained',
  'Bladeless Fan Warranty: What\'s Covered and What Isn\'t',
  'Reducing Dust Buildup Around Bladeless Fan Vents',
  'Bladeless Fans vs Air Conditioners: When Each Makes Sense',
  'Setting Up a Bladeless Fan Schedule With Smart Controls',
  'Common Bladeless Fan Myths, Debunked',
  'SpO2 and Heart Rate Monitoring: A Beginner\'s Guide',
  'How TheFutureX Monitoring Devices Track Recovery',
  'Resting Heart Rate: What\'s Normal and What\'s Not',
  'Understanding Heart Rate Variability HRV and Why It Matters',
  'Can Wearable Monitors Detect Irregular Heartbeats?',
  'How to Use Smart Monitoring Data to Improve Sleep',
  'Setting Up Health Alerts on Your TheFutureX App',
  'Smart Monitoring for Athletes: Training Load and Recovery',
  'What a Sudden SpO2 Drop Could Mean and When to See a Doctor',
  'Smart Monitoring Devices for Managing Stress Long-Term',
  'How Accurate Are At-Home Heart Rate Monitors Compared to Hospital Devices?',
  'Tracking Recovery After Illness With Smart Monitoring',
  'Smart Monitoring for Older Adults: What Families Should Know',
  'Understanding Your TheFutureX Weekly Health Report',
  'How Smart Monitoring Detects Overtraining',
  'Using Smart Monitoring Data Before and After Workouts',
  'Common Mistakes People Make Reading Their Health Data',
  'Smart Monitoring and Sleep Apnea: What Wearables Can and Can\'t Detect',
  'How to Share Monitoring Data With Your Doctor',
  'Smart Monitoring for Pregnant Women: What to Know',
  'Setting Personal Health Baselines With Smart Monitoring',
  'Why Consistency Matters More Than Single Readings',
  'Smart Monitoring for High-Altitude Travel',
  'How Body Temperature Tracking Works on Wearables',
  'Smart Monitoring Data Privacy: How TheFutureX Protects Your Information',
  'Building a Weekly Health Routine Around Your Monitoring Data',
  'Smart Monitoring for Shift Workers: Tracking Irregular Sleep',
  'How to Spot Early Signs of Burnout in Your Data',
  'Smart Monitoring vs Annual Checkups: Where Each Fits',
  'Getting Family Members Started With Smart Health Monitoring',
  'TFX AI Smart Glasses: Full Review After 2 Weeks',
  'How Bluetooth Calling Works on Smart Glasses',
  'Smart Glasses vs Earbuds: Which Is Better for Calls on the Go?',
  'Setting Up Voice Assistant on Your TFX Smart Glasses',
  'HD Recording on Smart Glasses: What You Need to Know',
  'Battery Life on AI Smart Glasses: What to Expect',
  'Can You Wear Smart Glasses With Prescription Lenses?',
  'Smart Glasses for Commuters: Hands-Free Music and Calls',
  'Smart Glasses Audio Quality: What Bone Conduction Actually Sounds Like',
  'Are Smart Glasses Good for Running and Workouts?',
  'Privacy and Recording Etiquette When Wearing Smart Glasses',
  'Smart Glasses Not Connecting? Troubleshooting Guide',
  'Smart Glasses for Cyclists: Safety and Convenience',
  'How Smart Glasses Compare to Smartwatches for Notifications',
  'Cleaning and Caring for Your Smart Glasses Lenses',
  'Smart Glasses Charging Case Explained',
  'Using Voice Commands to Control Music on Smart Glasses',
  'Smart Glasses for Remote Workers: Calls Without Headphones',
  'How Loud Can Smart Glasses Get in Noisy Environments?',
  'Smart Glasses Frame Materials: Durability Compared',
  'Are AI Smart Glasses Worth It If You Don\'t Wear Glasses Normally?',
  'Smart Glasses Firmware Updates: What They Improve',
  'Recording Quality in Low Light: What to Expect',
  'Smart Glasses for Travel: Hands-Free Navigation and Calls',
  'How Smart Glasses Handle Multiple Bluetooth Devices',
  'Smart Glasses Warranty and Common Replacement Parts',
  'Comparing TFX Smart Glasses Across Price Tiers',
  'Smart Glasses for Content Creators: Point-of-View Recording',
  'Do Smart Glasses Work Well With Sunglasses Lenses?',
  'Getting the Most Out of Your Smart Glasses in the First Week',
  'Building a Complete Wellness Routine: Tracking, Skin, and Recovery',
  'Why Hydration Quietly Wrecks Your Sleep and Recovery Scores',
  'What New Parents Should Know About Smart Monitoring at Home',
  'What Actually Goes Into the Box: A Look at Sustainable Tech Packaging',
  'How Your TheFutureX Order Actually Gets to You',
];

const blogPlanRoutes = blogPlanTitles.map((title) => ({
  path: `/blog/${toBlogSlug(title)}`,
  label: title,
  changefreq: 'weekly',
  priority: '0.7',
}));

const seoAeoBlogRoutes = [
  { path: '/blog/how-does-a-bladeless-fan-work', label: 'How Does a Bladeless Fan Work?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/bladeless-fan-vs-regular-fan', label: 'Bladeless Fan vs Regular Fan: Safety, Noise & Power Compared', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-bladeless-fan-for-small-bedrooms', label: 'Best Bladeless Fan for Small Bedrooms in India', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/bladeless-fan-buying-guide', label: 'Bladeless Fan Buying Guide: Heating, Cooling & Purifier Options Explained', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-vs-smart-band', label: 'Smart Ring vs Smart Band: Which Should You Buy in 2026?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-sizing-guide', label: 'Smart Ring Sizing Guide: How to Measure Your Finger', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-heart-rate-accuracy', label: 'How Accurate Are Smart Ring Heart Rate Sensors?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/do-smart-rings-work-without-phone', label: 'Do Smart Rings Work Without a Phone Nearby?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/spo2-monitoring-explained', label: 'SpO2 Monitoring Explained: What Your Smart Band Is Measuring', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-smart-band-features-sleep-tracking', label: 'Best Smart Band Features for Sleep Tracking in India', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-heart-rate-accuracy-exercise', label: 'How Accurate Are Smart Band Heart Rate Sensors During Exercise?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/sports-modes-explained', label: '100+ Sports Modes Explained: Which Ones Do You Actually Need?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/ai-smart-glasses-vs-earbuds', label: 'AI Smart Glasses vs Earbuds for Calls & Music: Which Wins?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/what-can-ai-smart-glasses-do', label: 'What Can AI Smart Glasses Actually Do? Features Explained', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/heart-rate-training-zones-explained', label: 'Heart Rate Zones Explained: How to Train Smarter with a Wearable', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/can-a-smart-band-detect-irregular-heartbeat-afib', label: 'Can a Smart Band Detect an Irregular Heartbeat or AFib?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-gps-accuracy-without-phone', label: 'Smart Band GPS Accuracy: Does It Track Runs Without Your Phone?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-family-sharing-tracking', label: 'Smart Band Family Sharing: Tracking Kids\' or Parents\' Activity Safely', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-do-not-disturb-sleep-mode-guide', label: 'Smart Band Do Not Disturb and Sleep Mode: Full Settings Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/syncing-smart-band-google-fit-apple-health', label: 'Syncing Your Smart Band to Google Fit or Apple Health', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/running-cadence-stride-length-smart-band', label: 'Understanding Running Cadence and Stride Length on Your Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-altitude-barometer-sensor-explained', label: 'Smart Band Altitude and Barometer Sensor: What It\'s Actually For', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-guided-breathing-meditation-features', label: 'Smart Band as a Meditation Coach: Guided Breathing Features Explained', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-strap-length-wrist-size-guide', label: 'Choosing the Right Smart Band Strap Length for Larger or Smaller Wrists', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-gifting-guide', label: 'Smart Band Gifting Guide: Which Model Fits Which Person', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-muscle-recovery-data', label: 'Smart Band for Post-Workout Muscle Recovery: What the Data Tells You', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-screen-brightness-battery-tradeoff', label: 'Smart Band Screen Brightness and Battery Life: Finding the Right Balance', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/first-week-with-your-new-smart-band', label: 'First Week With Your New Smart Band: What to Expect', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-desk-workers-move-reminders', label: 'Smart Band for Desk Workers: Reminders to Move and Stretch', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-accuracy-cold-weather', label: 'Smart Band Data Accuracy in Cold Weather: What Changes', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-for-typing-gaming-office-work', label: 'Can You Wear a Smart Ring If You Type All Day? A Gamer/Office Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-app-permissions-data-collected', label: 'Smart Ring App Permissions: What Data It Actually Collects', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-resizing-after-purchase', label: 'Smart Ring Resizing: What to Do If Your Size Feels Wrong After Wearing It', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-cold-weather-battery-accuracy', label: 'Smart Ring in Extreme Cold: Does Winter Affect Battery or Accuracy?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/first-time-smart-ring-buyer-checklist', label: 'First-Time Smart Ring Buyer\'s Checklist: 7 Things to Confirm Before You Order', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-readiness-score-workout-planning', label: 'How Smart Ring Readiness Scores Should Actually Change Your Workout Plan', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-subscription-free-vs-paid-features', label: 'Do Smart Rings Require a Subscription? Comparing Free vs Paid Features', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-gifting-anniversary-milestone-guide', label: 'Smart Ring Gifting for Anniversaries and Milestones: A Practical Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-notification-buzz-patterns-explained', label: 'Smart Ring Notification Types: Buzz Patterns Explained', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-metal-allergy-safe-wear', label: 'Smart Ring and Metal Allergies: How to Wear One Safely', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-vs-fitness-watch-battery-comparison', label: 'Smart Ring vs Regular Fitness Watch: A Battery Life Comparison', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-which-finger-to-wear', label: 'Can You Wear a Smart Ring on Any Finger? Placement Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-charging-habits-every-night', label: 'Smart Ring Charging Habits: Should You Charge It Every Night?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-travelers-tsa-timezones-syncing', label: 'Smart Ring for Travelers: TSA, Time Zones, and Syncing on the Go', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-sweat-exercise-damage', label: 'Smart Ring Skin Contact and Sweat: Does Exercise Damage It?', changefreq: 'weekly', priority: '0.7' },
];

const dedupeRoutes = (routes) => {
  const byPath = new Map();
  routes.forEach((route) => byPath.set(route.path, route));
  return [...byPath.values()];
};

const rawInfoRoutes = [
  { path: '/info/about-us', label: 'About Us', changefreq: 'monthly', priority: '0.5' },
  { path: '/info/contact', label: 'Contact', changefreq: 'monthly', priority: '0.5' },
  { path: '/info/shipping', label: 'Shipping Policy', changefreq: 'monthly', priority: '0.5' },
  { path: '/info/register-policy', label: 'Product Registration Policy', changefreq: 'monthly', priority: '0.5' },
  { path: '/info/warranty-policy', label: 'Warranty Policy', changefreq: 'monthly', priority: '0.5' },
  { path: '/info/returns-refund', label: 'Return & Refund Policy', changefreq: 'monthly', priority: '0.5' },
  { path: '/info/privacy', label: 'Privacy Policy', changefreq: 'monthly', priority: '0.4' },
  { path: '/info/terms', label: 'Terms of Service', changefreq: 'monthly', priority: '0.4' },
  { path: '/blog', label: 'TheFutureX Blog', changefreq: 'weekly', priority: '0.7' },
  { path: '/info/technology-behind-the-future-x', label: 'Technology Behind The Future X', changefreq: 'monthly', priority: '0.6' },
  { path: '/info/why-choose-the-future-x', label: 'Why Choose The Future X', changefreq: 'monthly', priority: '0.6' },
  { path: '/blog/what-is-a-smart-ring', label: 'What Is a Smart Ring?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/how-do-smart-rings-work', label: 'How Do Smart Rings Work?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/benefits-of-smart-rings', label: 'Benefits of Smart Rings', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-vs-smartwatch', label: 'Smart Ring vs Smartwatch', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-smart-ring-features', label: 'Best Smart Ring Features', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-smart-ring-for-sleep-tracking', label: 'Best Smart Ring for Sleep Tracking', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-heart-rate-monitoring', label: 'Smart Ring Heart Rate Monitoring', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-for-fitness-tracking', label: 'Smart Ring for Fitness Tracking', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-for-men', label: 'Smart Ring for Men', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-for-women', label: 'Smart Ring for Women', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/what-is-a-smart-band', label: 'What Is a Smart Band?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-vs-smartwatch', label: 'Smart Band vs Smartwatch', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/benefits-of-smart-bands', label: 'Benefits of Smart Bands', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-smart-band-features', label: 'Best Smart Band Features', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-smart-band-for-fitness-tracking', label: 'Best Smart Band for Fitness Tracking', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-heart-rate-monitoring', label: 'Smart Band Heart Rate Monitoring', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-smart-band-for-sleep-tracking', label: 'Best Smart Band for Sleep Tracking', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/do-screenless-smart-bands-track-health-well', label: 'Do Screenless Smart Bands Track Health Well?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/basic-fitness-band-vs-ai-smart-band', label: 'Basic Fitness Band vs AI Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/spo2-tracking-in-smart-bands', label: 'SpO2 Tracking in Smart Bands', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/hrv-and-stress-tracking-smart-band', label: 'HRV and Stress Tracking Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/sleep-tracking-smart-band-sleep-score', label: 'Sleep Tracking Smart Band Sleep Score', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/ip68-vs-5atm-smart-band', label: 'IP68 vs 5ATM Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/ai-coach-smart-band-explained', label: 'AI Coach Smart Band Explained', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-real-battery-life', label: 'Smart Band Real Battery Life', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/recovery-and-strain-tracking-wearable', label: 'Recovery and Strain Tracking Wearable', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-buying-guide-india-2026', label: 'Smart Band Buying Guide India 2026', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/what-is-bioage-smart-band', label: 'What Is BioAge on a Smart Band?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/mood-tracking-smart-band', label: 'Mood Tracking Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/wearable-blood-pressure-insights', label: 'Wearable Blood Pressure Insights', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/tfx5-companion-app-walkthrough', label: 'TFX5 Companion App Walkthrough', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-step-count-calorie-accuracy', label: 'Smart Band Step Count and Calorie Accuracy', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/wearing-smart-band-24-7', label: 'Wearing Smart Band 24/7', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-women-health-tracking', label: 'Smart Band for Women Health Tracking', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-beginners-data-guide', label: 'Smart Band for Beginners Data Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/tfx5-metal-vs-rubber-band', label: 'TFX5 Metal vs Rubber Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-warranty-support-india', label: 'Smart Band Warranty Support India', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-office-workers', label: 'Smart Bands for Office Workers', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-vs-manual-fitness-journaling', label: 'Smart Band vs Manual Fitness Journaling', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/understanding-resting-heart-rate-smart-band', label: 'Understanding Resting Heart Rate on a Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-weight-loss', label: 'Smart Band for Weight Loss', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-notifications-useful-alerts', label: 'Smart Band Notifications and Useful Alerts', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/how-long-do-smart-bands-last', label: 'How Long Do Smart Bands Last?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-charging-habits-battery-life', label: 'Smart Band Charging Habits and Battery Life', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-yoga-and-meditation', label: 'Smart Band for Yoga and Meditation', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/ai-powered-smart-band-explained-2026', label: 'AI-Powered Smart Band Explained 2026', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-return-exchange-policy', label: 'Smart Band Return and Exchange Policy', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-strap-replacement-care', label: 'Smart Band Strap Replacement and Care', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-students', label: 'Smart Band for Students', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-cyclists', label: 'Smart Band for Cyclists', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-swimmers', label: 'Smart Band for Swimmers', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/screenless-band-status-indicator', label: 'Screenless Band Status Indicator', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-intermittent-fasting', label: 'Smart Band and Intermittent Fasting', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-shift-workers', label: 'Smart Band for Shift Workers', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-firmware-update-guide', label: 'Smart Band Firmware Update Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-size-fit-guide', label: 'Smart Band Size and Fit Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-bands-for-couples-families', label: 'Smart Bands for Couples and Families', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/optical-heart-rate-sensor-smart-band', label: 'Optical Heart Rate Sensor Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/skin-temperature-vs-body-temperature-smart-band', label: 'Skin Temperature vs Body Temperature Smart Band', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-recovery-score-after-workout', label: 'Smart Band Recovery Score After Workout', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/tfx5-unboxing-first-setup', label: 'TFX5 Unboxing and First Setup', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-strap-color-guide', label: 'Smart Band Strap Color Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-price-comparison-india', label: 'Smart Band Price Comparison India', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-frequent-travelers', label: 'Smart Band for Frequent Travelers', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-sensitive-skin-materials', label: 'Smart Band Sensitive Skin Materials', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-vs-phone-fitness-apps', label: 'Smart Band vs Phone Fitness Apps', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/tfx5-long-term-review-3-months', label: 'TFX5 Long-Term Review 3 Months', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-men', label: 'Smart Band for Men', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-band-for-women', label: 'Smart Band for Women', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/are-smart-bands-worth-buying', label: 'Are Smart Bands Worth Buying?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/what-is-a-bladeless-fan', label: 'What Is a Bladeless Fan?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/bladeless-fan-vs-traditional-fan', label: 'Bladeless Fan vs Traditional Fan', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/benefits-of-bladeless-fans', label: 'Benefits of Bladeless Fans', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/how-does-a-bladeless-fan-work', label: 'How Does a Bladeless Fan Work?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/are-bladeless-fans-energy-efficient', label: 'Are Bladeless Fans Energy Efficient?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-bladeless-fan-for-home-use', label: 'Best Bladeless Fan for Home Use', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/bladeless-fan-for-bedroom', label: 'Bladeless Fan for Bedroom', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/bladeless-fan-with-air-purifier', label: 'Bladeless Fan with Air Purifier', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/are-bladeless-fans-safe-for-children-and-pets', label: 'Are Bladeless Fans Safe for Children and Pets?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-bladeless-fan-in-india', label: 'Best Bladeless Fan in India', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/complete-guide-to-fitness-heart-rate-monitoring', label: 'Complete Guide to Fitness Heart Rate Monitoring', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/why-athletes-use-chest-strap-heart-rate-monitors', label: 'Why Athletes Use Chest Strap Heart Rate Monitors', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/heart-rate-monitor-accuracy-chest-strap-vs-wrist-sensors', label: 'Heart Rate Monitor Accuracy: Chest Strap vs Wrist Sensors', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/heart-rate-training-zones-explained', label: 'Heart Rate Training Zones Explained', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-heart-rate-monitor-for-running-and-cycling', label: 'Best Heart Rate Monitor for Running and Cycling', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/benefits-of-bluetooth-heart-rate-monitoring', label: 'Benefits of Bluetooth Heart Rate Monitoring', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/how-heart-rate-tracking-improves-workout-performance', label: 'How Heart Rate Tracking Improves Workout Performance', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/why-serious-athletes-prefer-chest-belt-heart-rate-monitors', label: 'Why Serious Athletes Prefer Chest Belt Heart Rate Monitors', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/heart-rate-monitor-buying-guide', label: 'Heart Rate Monitor Buying Guide', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/what-is-sleep-monitoring', label: 'What Is Sleep Monitoring?', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/how-sleep-tracking-works', label: 'How Sleep Tracking Works', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/benefits-of-sleep-monitoring', label: 'Benefits of Sleep Monitoring', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/sleep-stages-explained', label: 'Sleep Stages Explained', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/how-sleep-monitoring-helps-improve-recovery', label: 'How Sleep Monitoring Helps Improve Recovery', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-vs-smart-band-for-sleep-tracking', label: 'Smart Ring vs Smart Band for Sleep Tracking', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/best-sleep-tracker-in-2026', label: 'Best Sleep Tracker in 2026', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/how-sleep-quality-affects-fitness-performance', label: 'How Sleep Quality Affects Fitness Performance', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/smart-ring-sleep-tracking-vs-smartwatch-sleep-tracking', label: 'Smart Ring Sleep Tracking vs Smartwatch Sleep Tracking', changefreq: 'weekly', priority: '0.7' },
  { path: '/blog/thefuturex-smart-sleep-tracking-monitoring-system', label: 'TheFutureX Smart Sleep Tracking Monitoring System', changefreq: 'weekly', priority: '0.7' },
  ...seoAeoBlogRoutes,
  ...blogPlanRoutes,
];

export const infoRoutes = dedupeRoutes(rawInfoRoutes);
const publishedBlogRoutes = [
  { path: '/blog/activity-tracker-band-guide', label: 'Activity Tracker Band Guide', changefreq: 'monthly', priority: '0.7' },
  { path: '/blog/best-smart-bands-under-10000-india', label: 'Best Smart Bands Under ₹10,000 in India', changefreq: 'monthly', priority: '0.7' },
  { path: '/blog/what-is-spo2-monitoring', label: 'What Is SpO2 Monitoring?', changefreq: 'monthly', priority: '0.7' },
  { path: '/blog/smart-band-vs-smartwatch', label: 'Smart Band vs Smartwatch', changefreq: 'monthly', priority: '0.7' },
  { path: '/blog/best-bladeless-fans-india-2026', label: 'Best Bladeless Fans for Indian Homes', changefreq: 'monthly', priority: '0.7' },
];
// Only publish pages that are real, maintained destinations.  The previous
// sitemap included hundreds of planned/generated blog URLs with substantially
// the same content; that creates crawl waste and thin-page signals. Blog posts
// are added to the sitemap only when they are published as full pages.
export const sitemapRoutes = [
  ...coreRoutes,
  { path: '/blog', label: 'TheFutureX Blog', changefreq: 'weekly', priority: '0.7' },
  ...publishedBlogRoutes,
];

// Do not generate fallback files for retired/blog-plan URLs. Unknown legacy
// URLs must be allowed to return a genuine 404 at the host, rather than a
// client-side page that looks like a soft 404 to Google.
const legacyBlogFallbackRoutes = [];

export const spaFallbackRoutes = [
  // Active campaign route: keep a concrete fallback so direct visits and
  // refreshes load the site shell before the /offers/:slug route hydrates.
  'offers/exchange-bonusv',
  'delete-account',
  'cart',
  'checkout',
  'verify-phone',
  'payment',
  'order-success',
  'track-order',
  'login',
  'signup',
  'profile',
  'shop',
  ...sitemapRoutes.map((route) => route.path.replace(/^\//, '')).filter(Boolean),
  // InfoPage is served by the /info/:slug client route. Generate concrete
  // fallbacks for every maintained info page so direct visits and refreshes
  // reach the SPA on hosts without a rewrite rule.
  ...infoRoutes.map((route) => route.path.replace(/^\//, '')).filter(Boolean),
  ...legacyBlogFallbackRoutes,
  ...[...new Set(staticProductSeoRecords
    .map((product) => product.canonicalSlug || product.slug)
    .filter(Boolean)
    .map((slug) => `product/${slug}`))],
];
